/**
 * ESLint configuration (flat config).
 *
 * Built on `eslint-config-expo`, which already knows about React Native, hooks,
 * and the Expo module resolver. Everything below is either a rule this codebase
 * actually relies on, or a deliberate relaxation with the reason attached —
 * a config full of rules nobody chose is a config nobody reads.
 */

const expoConfig = require('eslint-config-expo/flat');
const prettier = require('eslint-config-prettier');
// Flat config requires a plugin to be registered in the same config object that
// uses its rules — inheriting it from a spread-in config is not enough.
const tsPlugin = require('@typescript-eslint/eslint-plugin');

module.exports = [
  ...expoConfig,
  prettier,
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'coverage/**',
      'src/data/levels/index.ts', // generated by `npm run levels:build`
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      // The domain layer returns typed `Result` values instead of throwing, and
      // several I/O wrappers deliberately swallow errors. An empty catch is a
      // decision here, not an oversight — but it must be a *visible* one, so
      // require a comment inside rather than allowing a bare `{}`.
      'no-empty': ['error', { allowEmptyCatch: false }],

      // Unused variables are almost always a leftover, except for the
      // intentionally-discarded ones in destructuring, which are prefixed.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
          ignoreRestSiblings: true,
        },
      ],

      // `console` is fine behind a `__DEV__` guard, which the storage layer uses
      // to make a save failure visible in development and silent in production.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Off-device tooling is a Node program: it prints, it reads files, and it
    // exits with a code. None of that belongs in the app, but all of it is
    // correct here.
    files: ['tools/**/*.ts', '*.config.js', 'jest.setup.js'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // Test files and the Jest setup run under Jest's globals.
    files: ['__tests__/**/*.ts', '__tests__/**/*.tsx', 'jest.setup.js'],
    languageOptions: {
      globals: {
        jest: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
  },
];
