/**
 * index.ts — the shipped level library.
 *
 * GENERATED by `npm run levels:build`. Do not edit by hand; your changes will be
 * overwritten and, worse, will not have been checked by the solver.
 */

import type { LevelDefinition } from '@game';

import level001 from './001.json';
import level002 from './002.json';
import level003 from './003.json';
import level004 from './004.json';
import level005 from './005.json';
import level006 from './006.json';
import level007 from './007.json';
import level008 from './008.json';
import level009 from './009.json';
import level010 from './010.json';
import level011 from './011.json';
import level012 from './012.json';
import level013 from './013.json';
import level014 from './014.json';
import level015 from './015.json';
import level016 from './016.json';
import level017 from './017.json';
import level018 from './018.json';
import level019 from './019.json';
import level020 from './020.json';
import level021 from './021.json';
import level022 from './022.json';
import level023 from './023.json';
import level024 from './024.json';
import level025 from './025.json';
import level026 from './026.json';
import level027 from './027.json';
import level028 from './028.json';
import level029 from './029.json';
import level030 from './030.json';
import level031 from './031.json';
import level032 from './032.json';
import level033 from './033.json';
import level034 from './034.json';
import level035 from './035.json';
import level036 from './036.json';
import level037 from './037.json';
import level038 from './038.json';
import level039 from './039.json';
import level040 from './040.json';
import level041 from './041.json';
import level042 from './042.json';
import level043 from './043.json';
import level044 from './044.json';
import level045 from './045.json';
import level046 from './046.json';
import level047 from './047.json';
import level048 from './048.json';
import level049 from './049.json';
import level050 from './050.json';

/** Every level, in play order. */
export const LEVELS: readonly LevelDefinition[] = [
  level001 as LevelDefinition,
  level002 as LevelDefinition,
  level003 as LevelDefinition,
  level004 as LevelDefinition,
  level005 as LevelDefinition,
  level006 as LevelDefinition,
  level007 as LevelDefinition,
  level008 as LevelDefinition,
  level009 as LevelDefinition,
  level010 as LevelDefinition,
  level011 as LevelDefinition,
  level012 as LevelDefinition,
  level013 as LevelDefinition,
  level014 as LevelDefinition,
  level015 as LevelDefinition,
  level016 as LevelDefinition,
  level017 as LevelDefinition,
  level018 as LevelDefinition,
  level019 as LevelDefinition,
  level020 as LevelDefinition,
  level021 as LevelDefinition,
  level022 as LevelDefinition,
  level023 as LevelDefinition,
  level024 as LevelDefinition,
  level025 as LevelDefinition,
  level026 as LevelDefinition,
  level027 as LevelDefinition,
  level028 as LevelDefinition,
  level029 as LevelDefinition,
  level030 as LevelDefinition,
  level031 as LevelDefinition,
  level032 as LevelDefinition,
  level033 as LevelDefinition,
  level034 as LevelDefinition,
  level035 as LevelDefinition,
  level036 as LevelDefinition,
  level037 as LevelDefinition,
  level038 as LevelDefinition,
  level039 as LevelDefinition,
  level040 as LevelDefinition,
  level041 as LevelDefinition,
  level042 as LevelDefinition,
  level043 as LevelDefinition,
  level044 as LevelDefinition,
  level045 as LevelDefinition,
  level046 as LevelDefinition,
  level047 as LevelDefinition,
  level048 as LevelDefinition,
  level049 as LevelDefinition,
  level050 as LevelDefinition,
];

/** Total levels shipped. */
export const LEVEL_COUNT = LEVELS.length;

/** Look up a level by its id (1-based), or `undefined`. */
export function levelById(id: number): LevelDefinition | undefined {
  return LEVELS.find((level) => level.id === id);
}
