/**
 * index.ts — the shipped level library.
 *
 * GENERATED by `npm run levels:build`. Do not edit by hand; your changes will be
 * overwritten and, worse, will not have been checked by the solver.
 *
 * Levels are stored compactly (see `game/codec`) and grouped into packs, so the
 * 1000 of them cost 20 Metro modules rather than 1000. Decoding happens
 * on demand and is cached, so only the levels actually played are ever expanded.
 */

import { decodeLevel, type EncodedLevel, type LevelPack, type DifficultyTier } from '@game/codec';
import type { LevelDefinition } from '@game';

import pack01 from './pack-01.json';
import pack02 from './pack-02.json';
import pack03 from './pack-03.json';
import pack04 from './pack-04.json';
import pack05 from './pack-05.json';
import pack06 from './pack-06.json';
import pack07 from './pack-07.json';
import pack08 from './pack-08.json';
import pack09 from './pack-09.json';
import pack10 from './pack-10.json';
import pack11 from './pack-11.json';
import pack12 from './pack-12.json';
import pack13 from './pack-13.json';
import pack14 from './pack-14.json';
import pack15 from './pack-15.json';
import pack16 from './pack-16.json';
import pack17 from './pack-17.json';
import pack18 from './pack-18.json';
import pack19 from './pack-19.json';
import pack20 from './pack-20.json';

const PACKS: readonly LevelPack[] = [
  pack01 as unknown as LevelPack,
  pack02 as unknown as LevelPack,
  pack03 as unknown as LevelPack,
  pack04 as unknown as LevelPack,
  pack05 as unknown as LevelPack,
  pack06 as unknown as LevelPack,
  pack07 as unknown as LevelPack,
  pack08 as unknown as LevelPack,
  pack09 as unknown as LevelPack,
  pack10 as unknown as LevelPack,
  pack11 as unknown as LevelPack,
  pack12 as unknown as LevelPack,
  pack13 as unknown as LevelPack,
  pack14 as unknown as LevelPack,
  pack15 as unknown as LevelPack,
  pack16 as unknown as LevelPack,
  pack17 as unknown as LevelPack,
  pack18 as unknown as LevelPack,
  pack19 as unknown as LevelPack,
  pack20 as unknown as LevelPack,
];

/** Every level in stored form, in play order. Cheap to hold; not yet decoded. */
export const ENCODED_LEVELS: readonly EncodedLevel[] = PACKS.flatMap((pack) => pack.levels);

/** Total levels shipped. */
export const LEVEL_COUNT = ENCODED_LEVELS.length;

const cache = new Map<number, LevelDefinition>();

/** Look up a level by its id (1-based), decoding and caching on first use. */
export function levelById(id: number): LevelDefinition | undefined {
  const hit = cache.get(id);
  if (hit) return hit;

  const encoded = ENCODED_LEVELS[id - 1];
  if (!encoded || encoded.i !== id) {
    const found = ENCODED_LEVELS.find((level) => level.i === id);
    if (!found) return undefined;
    const decoded = decodeLevel(found);
    cache.set(id, decoded);
    return decoded;
  }

  const decoded = decodeLevel(encoded);
  cache.set(id, decoded);
  return decoded;
}

/** Difficulty tier for a level, without decoding it. */
export function tierOf(id: number): DifficultyTier | undefined {
  return ENCODED_LEVELS[id - 1]?.t ?? ENCODED_LEVELS.find((l) => l.i === id)?.t;
}

/** Level name and board size, for level select — no decoding needed. */
export function summaryOf(id: number):
  | { name: string; rows: number; cols: number; tier: DifficultyTier; difficulty: number }
  | undefined {
  const level = ENCODED_LEVELS[id - 1]?.i === id
    ? ENCODED_LEVELS[id - 1]
    : ENCODED_LEVELS.find((l) => l.i === id);
  if (!level) return undefined;
  return { name: level.n, rows: level.r, cols: level.c, tier: level.t, difficulty: level.d };
}
