/**
 * build-levels.ts — generate the shipped level library.
 *
 * Purpose:      Turn the curriculum into `src/data/levels/NNN.json`, every one
 *               verified solvable with its canonical solution recorded.
 * Responsibilities:
 *               - Generate, verify, and write each level.
 *               - Print a curve report so the difficulty ramp can be eyeballed.
 * Notes:        Deterministic. Each level's seed is derived from its id, so
 *               rebuilding the library produces byte-identical files and a level
 *               a player has learned never silently changes underneath them.
 *
 *               A level is only written once the solver has both solved it *and*
 *               replayed its recorded solution. Nothing reaches `src/data` on
 *               trust.
 *
 *               Run: `npm run levels:build`
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildLevel, solve, verifySolution, type LevelDefinition } from '../src/game';
import { CURRICULUM, bandOf } from './curriculum';
import { generateLevel } from './generate';

const OUT_DIR = join(process.cwd(), 'src', 'data', 'levels');

/** Distinct, stable seed per level. */
const seedFor = (id: number): number => id * 7919 + 104729;

interface BuildResult {
  readonly level: LevelDefinition;
  readonly blindMistakes: number;
  readonly target: number;
  readonly arrows: number;
  readonly avgLen: number;
  readonly avgTurns: number;
}

function buildOne(planIndex: number): BuildResult {
  const plan = CURRICULUM[planIndex]!;

  // Widen the search on later attempts: a tight shape sometimes cannot hit its
  // target arrow count, and loosening beats shipping a level that missed its band.
  for (let relax = 0; relax < 4; relax += 1) {
    const candidate = generateLevel(
      seedFor(plan.id) + relax * 31,
      {
        rows: plan.rows,
        cols: plan.cols,
        shape: plan.shape,
        arrowCount: Math.max(3, plan.arrowCount - relax),
        minBodyLength: Math.max(2, plan.minBodyLength - (relax > 1 ? 1 : 0)),
        maxBodyLength: plan.maxBodyLength,
        targetBlindMistakes: plan.targetBlindMistakes,
        attempts: 1400,
        hearts: plan.hearts,
      },
      { id: plan.id, name: plan.name },
    );
    if (!candidate) continue;

    const built = buildLevel(candidate.level);
    if (!built.ok) throw new Error(`level ${plan.id}: ${built.error}`);

    const outcome = solve(built.value.board, built.value.initial);
    if (outcome.kind !== 'solved') {
      throw new Error(`level ${plan.id}: generator produced an unsolvable board`);
    }

    const check = verifySolution(built.value.board, built.value.initial, outcome.solution);
    if (!check.ok) throw new Error(`level ${plan.id}: ${check.error}`);

    const level: LevelDefinition = {
      ...candidate.level,
      solution: outcome.solution.map((i) => built.value.board.arrows[i]!.id),
    };

    return {
      level,
      blindMistakes: candidate.metrics.expectedBlindMistakes,
      target: plan.targetBlindMistakes,
      arrows: candidate.metrics.arrowCount,
      avgLen: candidate.metrics.avgBodyLength,
      avgTurns: candidate.metrics.avgTurns,
    };
  }

  throw new Error(
    `level ${plan.id} "${plan.name}": no solvable ${plan.shape} board found — ` +
      'loosen the plan (fewer arrows, shorter bodies, or a bigger grid)',
  );
}

mkdirSync(OUT_DIR, { recursive: true });

const results: BuildResult[] = [];
for (let i = 0; i < CURRICULUM.length; i += 1) {
  const result = buildOne(i);
  results.push(result);

  const file = join(OUT_DIR, `${String(result.level.id).padStart(3, '0')}.json`);
  writeFileSync(file, `${JSON.stringify(result.level, null, 2)}\n`, 'utf8');
}

// The index is generated too, so adding a level never means editing code by hand.
const imports = results
  .map((r) => `import level${String(r.level.id).padStart(3, '0')} from './${String(r.level.id).padStart(3, '0')}.json';`)
  .join('\n');
const list = results
  .map((r) => `  level${String(r.level.id).padStart(3, '0')} as LevelDefinition,`)
  .join('\n');

writeFileSync(
  join(OUT_DIR, 'index.ts'),
  `/**
 * index.ts — the shipped level library.
 *
 * GENERATED by \`npm run levels:build\`. Do not edit by hand; your changes will be
 * overwritten and, worse, will not have been checked by the solver.
 */

import type { LevelDefinition } from '@game';

${imports}

/** Every level, in play order. */
export const LEVELS: readonly LevelDefinition[] = [
${list}
];

/** Total levels shipped. */
export const LEVEL_COUNT = LEVELS.length;

/** Look up a level by its id (1-based), or \`undefined\`. */
export function levelById(id: number): LevelDefinition | undefined {
  return LEVELS.find((level) => level.id === id);
}
`,
  'utf8',
);

// ---------------------------------------------------------------------------
// Curve report
// ---------------------------------------------------------------------------

console.log(`Built ${results.length} levels into src/data/levels\n`);
console.log('  id  band          name           shape       size   arr  len  turn  blind (target)');
console.log('  ' + '-'.repeat(84));

for (const r of results) {
  const l = r.level;
  const drift = r.blindMistakes - r.target;
  const flag = Math.abs(drift) > Math.max(2, r.target * 0.45) ? ' <-- off target' : '';
  console.log(
    `  ${String(l.id).padStart(2)}  ${bandOf(l.id).padEnd(12)}  ${l.name.padEnd(13)}  ` +
      `${l.layout.padEnd(10)}  ${`${l.rows}x${l.cols}`.padEnd(5)}  ` +
      `${String(r.arrows).padStart(3)}  ${r.avgLen.toFixed(1)}  ${r.avgTurns.toFixed(1)}   ` +
      `${r.blindMistakes.toFixed(1).padStart(5)} (${r.target.toFixed(1)})${flag}`,
  );
}

const offTarget = results.filter(
  (r) => Math.abs(r.blindMistakes - r.target) > Math.max(2, r.target * 0.45),
);
console.log(
  `\n${results.length - offTarget.length}/${results.length} levels landed within their difficulty band.`,
);
if (offTarget.length > 0) {
  console.log('Off-target levels are still solvable and playable — retune their plan if the feel is wrong.');
}
